version: "3"

services:
  my_app:
    build:
      context: .
    # ports:
    #   - "8000:8000"
    volumes:
       - .:/app
    # network_mode: host
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    
